### ISSUE TITLE
to the creator

### ISSUE THREAD

**Issue by bullocksedwardo** [SChernykh/p2pool#107]
Seth,  I have been watching the ins and outs of the mining and logs etc.  I have come to the conclusion that you are cheating me out of the blocks my computer has found.  And not just one but the latest was number ending in #####.  Thats not fare that you cheat me out of my legitim finds while mining on your pool.  Quite frankly I don't care that you all in the pool business cheat people, but you have made it very clear that this pool isn't like that when indeed it is.  Pay me for all the blocks I have found its only fare.  Yes, I sat and watched this for the last 12 hours or so since I logged in to your pool again this morning for the second time this month.  Greed is a bad virus...and it appears you caught that virus...please pay me the blocks my computer has found

**Comment by SChernykh** [comment]
Neither me nor anyone else control the pool payouts, and this is by design. Please read again how it works: https://github.com/SChernykh/p2pool#how-pplns-works-in-p2pool
And it's not "my" pool, also by design. I only provide the software. If you have p2pool.log left, check when you found a share and when p2pool found a block, and if your share was in the PPLNS window but you wasn't paid for some reason, we can start investigating from there. I need the lines from log around the share you found so I could see the share ID and p2pool height. Maybe you were out of sync and other p2pool nodes didn't see your share, maybe something else happened.

**Comment by ar-** [comment]
I have comments in addition to what @SChernykh said. True, cheating is not possible unlike in all other pools. The authors seems to have bad experiences and aims to be very skeptical now. 

@SChernykh 
I think the reporter might have a misunderstanding of the green outputs. It says "share found" and "BLOCK FOUND". He might think, that he shall receive a whole block reward now.

@bullocksedwardo 
Can you elaborate, how you come to that conclusion? You say " I have been watching the ins and outs of the mining and logs" ... what did the logs tell you ? What was your expectation?

**Comment by EDad-v2** [comment]
It's unfair to blindly accuse the author of cheating you. Read the code, it's right here for everyone to review. There is no skimming, hidden fees and nowhere does any surplus of any kind get sent anywhere other than to the wallets of the deserving miners.

I'm sure you are frustrated. I get it. But this post of yours damages the p2pool community and it's not fair. Please consider taking it down.

**Comment by bullocksedwardo** [comment]
okay well why onthe p2pool it showing i have mined three blocks but have been paid pennies

**Comment by bullocksedwardo** [comment]
something is not quite right

**Comment by bullocksedwardo** [comment]
and to go along with some of the other comments left about not being in sync is when  i was mining those blocks that my computer found.  i just want what is fare

**Comment by bullocksedwardo** [comment]
here lies another issue on p2pool website i can never find my shares being submitted only being submitted by about 3 address always no matter how many times i refresh the screen and those are the same address that are getting credit for the blocks so something is way off here.  to many excuses and no money being paid to the people actually submitting shares which i submitted 80,000 share in about a 24 hour period

**Comment by SChernykh** [comment]
> okay well why onthe p2pool it showing i have mined three blocks going just by what i said above but have been paid pennies only about 20 times

You didn't mine 3 blocks, the pool mined 3 blocks. This is why you see different address of who mined these blocks at p2pool.observer. You got your portion of each block's rewards, proportional to the number of p2pool shares you had in the PPLNS window at the time. Read above comments and read https://github.com/SChernykh/p2pool#how-pplns-works-in-p2pool

**Comment by p2pool-uk** [comment]
Think of p2pool as a Syndicated Lottery whereby you buy (mine) a ticket (share) to be included in any winnings (blocks found) that the syndicate (p2pool network) gets.
You will receive a payment for each share you have in the PPLNS window when a block is found.
Yes, each share is worth pennies per block found currently; But rather than have those pennies build up in a shared wallet until you reach a certain threshold before you can cash them out, you get sent them straight to your wallet immediately without any fees.
No one holds onto your winnings, no fees are taken, there's nothing hidden in the code for developers to siphon off any work done by your miners, or any payments you have earned. If you lack the trust to believe me, the code is literally there to look at and scrutinize.

**Comment by ar-** [comment]
@bullocksedwardo 
>  I have been watching the ins and outs of the mining and logs etc

You have clearly not done that. So, right now, the only one cheating is you. You are also not able to say what exactly you saw in the logs and how you came to the conclusion. You are rather ignoring us and it looks like a useless rant. Try to stick with the facts.

You say you have submitted 80000 shares in 24 hours. The pool is calibrated to have around (2160*4=) 8640 shares in 24 hours. If you submitted one of them there is currently a very high chance that you received one (or many) small payments for it. I think you have just set your xmrig to a very small min difficulty and now you see a lot of "accepted" messages in your xmr rig.

But again: how did you get the number 80000 ? If you saw that number in the status of p2pool, you have likely changed the config file and you are effectively solo-mining.

And I read this here:

> okay well why on the p2pool it showing i have mined three blocks going just by what i said above but have been paid pennies only about 20 times

around 50 times. And have still no idea what you are trying to say. Have you been paid anything or not ?

**Comment by westz36** [comment]
code is open source, trust but verify. you have not done that here, no evidence on your claim, its just your opinion, man. lol
