### ISSUE TITLE
submit_block (external blob): daemon returned error: unknown error

### ISSUE THREAD

**Issue by gnif** [SChernykh/p2pool#199]
I am new to this project so please forgive me if I am asking things that are obvious. I was not able to use the pre-compiled binaries provided as they segfault so instead I built the project as per the build instructions. It seems to be working fine, but I am getting the error `submit_block (external blob): daemon returned error: unknown error` randomly, and seeing it happen at the same time it found a block has me concerned that I will have lost out on the reward for this.

![2022-08-18-134633_911x131_scrot](https://user-images.githubusercontent.com/351151/185290450-5cb1e40a-c1e4-4826-99b6-23da9a5e184a.png)

Is this something I should be concerned about? and if so, what do I need to do in order to correct it?

**Comment by gnif** [comment]
I have rolled back to the v2.2.1 tag to see if this problem persists.

**Comment by SChernykh** [comment]
This is normal, it happens when you try to submit a block found by another p2pool node and your node doesn't have some transactions from that block. It doesn't affect mining. The original p2pool node have already submitted this block to Monero network. This error just means that your node's attempt to propagate the block faster failed.

**Comment by gnif** [comment]
Understood, thanks for the prompt reply and information!
