### ISSUE TITLE
p2pool seems to be causing monerod to fall out of sync and never catch up

### ISSUE THREAD

**Issue by snex** [SChernykh/p2pool#209]
Not really sure what's causing this, but it happens occasionally after the 0.18 update. I will wake up and p2pool is complaining about monerod being out of sync. I shut down p2pool and then monerod will catch up no problem.

**Comment by SChernykh** [comment]
I see two possibilities:

It can be miner taking too much CPU so monerod can't keep up, or p2pool + monerod didn't fit in RAM so monerod slowed down because of disk swapping. And if it's not on SSD, it would make this much worse.

Or it can be too many incoming connections (more than 1024) piling up over time, so monerod ran out of open files limit and all sorts of strange things started happening.

**Comment by snex** [comment]
My resources seem fine so it might be the 2nd one - I will limit in-peers and see if it happens again. Thanks.

**Comment by snex** [comment]
Ok so turns out I am actually behind a firewall and therefore my in-peers is always at 0. Might it be worthwhile to have a command line option that tells p2pool to skip the call to handle_incoming_block_async in p2p_server.cpp when the peer_height doesn't match our_height? I could probably write the code for that but I'm not sure how I would test it.

**Comment by SChernykh** [comment]
This logic already exists: https://github.com/SChernykh/p2pool/blob/master/src/p2p_server.cpp#L1892
Changing it to completely discard everything that doesn't match current height will quickly lead to p2pool chain split, so it's a no go. It's better to fix your monerod issues.

**Comment by snex** [comment]
Is there a valid reason to continue processing when the peer_height is greater than our_height by some significant amount? The function will early return false when we are unreasonably stale (our_height is more than 5 ahead of peer_height), but it never does an early return no matter how far behind we are.

**Comment by SChernykh** [comment]
The current logic was refined during initial tests and first few months of operation, you can check github commits. If lagging peers banned normal peers because they are too far ahead, then lagging peers would mine on top of old p2pool blocks -> chain split, and all their mined blocks would be orphaned. When normal peers ban lagging peers it doesn't result in chain split because lagging peers would still receive latest blocks from other random peers which didn't ban them yet.

**Comment by bladedoyle** [comment]
I am also having issues with monerod falling out of sync while running p2pool-mini, though I dont know that the issue is related to p2pool.  Restarting monerod temporarily gets things working again. 
```
2022-10-20 15:19:40.3290 SideChain add_external_block: block is built on top of an unknown mainchain block 591fa0ee5e4a2f92d8ccdb3cf821fb78abd451cd7edc70fdb091b6ffa42ec265, mainchain reorg might've happened
2022-10-20 15:19:40.3402 SideChain add_external_block: couldn't get mainchain difficulty for height = 2737692
2022-10-20 15:19:40.4587 P2PServer Trying to broadcast a block b2cc3838395d3622583c6e4e7636138022cab7f03dfdf228cf2b8d72271cb841 ahead on mainchain (mainchain height 2737692, current height is 2737514)
2022-10-20 15:19:40.4592 P2PServer peer 103.16.181.169:37888 is ahead on mainchain (height 2737692, your height 2737514). Is your monerod stuck or lagging?
```
I'll look at monerod to see if I can find if I have any issues there.

**Comment by SChernykh** [comment]
@snex Do you have any updates?

**Comment by snex** [comment]
I have not seen the issue since I first posted, and there have been a few chances for it to happen as well since my internet went down and I was out of sync for a few hours, but everything came back on its own.

**Comment by snex** [comment]
So, odd thing. Last night internet went out for a bit, and when I woke up p2pool was insisting that monerod was out of sync despite it having resynced just fine after the internet came back. Restarting p2pool brought it back online immediately.

I also haven't nabbed a share in about a week, despite my average share time being 1 every 1.5 days. Not sure if I'm just having extreme bad luck, there is more competition and the calculator hasn't taken that into account, or if there's an actual problem happening.
