### ISSUE TITLE
Finding blocks but not Rewards

### ISSUE THREAD

**Issue by amzinglyrwarded** [SChernykh/p2pool#210]
Quick Question. 
I've found over 8 shares of p2pool in the past 5 days. And only got rewarded for 1. (3 days ago)

Is this common? Could I be doing something wrong?

**Comment by SChernykh** [comment]
Please read https://github.com/SChernykh/p2pool#how-pplns-works-in-p2pool
I will assume you're mining on p2pool mini because you found a lot of shares, but not so many payouts. P2Pool mini doesn't find blocks often enough to pay for every share, but it doesn't mean you're getting paid less - you still find a lot more shares. It averages out to the same XMR amount over long period of time, and it depends only on your hashrate.

Now, if you think that you found some share and then P2Pool found a block in less than 2160 sidechain blocks (~6 hours), check https://mini.p2pool.observer/ for you address and give me a link to that share, I'll look into it.

**Comment by SChernykh** [comment]
I take no answer as everything working fine on p2pool side.

**Comment by amzinglyrwarded** [comment]
Yes, funny how as soon as I asked the question I had 4 or 5 payouts come in back to back. Luck is a swift mistress.
