### ISSUE TITLE
CMake build error on NixOS

### ISSUE THREAD

**Issue by Necryotiks** [SChernykh/p2pool#80]
Hello,

When I attempt to build p2pool using the following command:
```
nix run git+https://github.com/SChernykh/p2pool?ref=master -- --help
```
I get the following error:
```
error: builder for '/nix/store/2dwhn0f5xpnzbypv1w9l9djqsmdaz84i-p2pool-0.0.1.drv' failed with exit code 1;
       last 10 log lines:
       > CMake Error at CMakeLists.txt:12 (add_subdirectory):
       >   The source directory
       >
       >     /build/source/external/src/RandomX
       >
       >   does not contain a CMakeLists.txt file.
       >
       >
       > -- Configuring incomplete, errors occurred!
       > See also "/build/source/build/CMakeFiles/CMakeOutput.log".
       For full logs, run 'nix log /nix/store/2dwhn0f5xpnzbypv1w9l9djqsmdaz84i-p2pool-0.0.1.drv'.
```

Is there anything I am forgetting to do?
I know that there is a merge request for p2pool in the pipeline but I'm not sure when that will be complete.

NixOS Version: 21.11pre333218.263ef4cc414 (Porcupine)

**Comment by SChernykh** [comment]
Did you try instructions at https://github.com/SChernykh/p2pool#nixnixos ? Also I have no idea for it works, maybe @HaosGames can help.

**Comment by HaosGames** [comment]
Yeah, this is currently broken because the support for git-submodules in nix-flakes [got reverted](https://github.com/NixOS/nix/pull/5284). There is a [tracking issue](https://github.com/NixOS/nix/issues/5312) for fixing this but it may take a while to find the right solution. 
Now that you mention the [pull request in nixpkgs](https://github.com/NixOS/nixpkgs/pull/146623) I think it may be better to wait for it to be merged because even if I was trying to fix this now it probably would not be a proper fix because nix still lacks a proper solution for git-submodules in nix-flakes. 

I however found [this](https://github.com/NixOS/nix/pull/5434) PR which introduces a "build-with-submodules"-flag in the URL. So for now you could try this:
1. Enter a shell with the latest nix from the master branch
`nix shell github:nixos/nix/master`
2. Then build or/and run p2pool with the submodules flag
`nix run git+https://github.com/SChernykh/p2pool?submodules=1`

**Comment by ratsclub** [comment]
I created the PR because I had the same problem. I'm currently in the step of testing it for a few days to see if it's working properly and I'd really appreciate it if you people tried it on your setup too!

**Comment by ratsclub** [comment]
Hello, I did [a little project](https://github.com/nixosbrasil/nix-monero) meant to provide these packages. It has the latest `xmrig` software and `p2pool`. It also has the monero node on the current `release-v0.17` branch commit.

Although it doesn't have much documentation I'll say that you can just import the overlay on your configuration and use all the packages!

**Comment by Owlsystem** [comment]
same error

**Comment by ratsclub** [comment]
It was merged on nixpkgs. One can use it right from there!
